server:
  port: 7001

spring:
  application:
    name: demo-sharding-java-order-service

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.yx.demo.shardingsphere.domain

